name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Only run the workflow if files in the web-client directory change
    paths:
      - 'form-puck/web-client/**'

# Grants permissions to push to the gh-pages branch
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./form-puck/web-client
        run: npm ci

      - name: Build project
        working-directory: ./form-puck/web-client
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./form-puck/web-client/dist
